// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University.Tuition.Api.Infrastructure.Data;

#nullable disable

namespace University.Tuition.Api.Migrations
{
    [DbContext(typeof(TuitionDbContext))]
    [Migration("20251122172926_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University.Tuition.Api.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Term");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 3000.00m,
                            CreatedAt = new DateTime(2025, 11, 22, 17, 29, 26, 400, DateTimeKind.Utc).AddTicks(1862),
                            StudentId = 1,
                            Term = "2025-Spring"
                        });
                });

            modelBuilder.Entity("University.Tuition.Api.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNo")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Selin Yılmaz",
                            StudentNo = "20201234"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Ahmet Demir",
                            StudentNo = "20204567"
                        });
                });

            modelBuilder.Entity("University.Tuition.Api.Domain.Entities.TuitionCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Term");

                    b.ToTable("TuitionCharges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12000.00m,
                            CreatedAt = new DateTime(2025, 11, 22, 17, 29, 26, 400, DateTimeKind.Utc).AddTicks(1847),
                            StudentId = 1,
                            Term = "2025-Spring"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 9000.00m,
                            CreatedAt = new DateTime(2025, 11, 22, 17, 29, 26, 400, DateTimeKind.Utc).AddTicks(1850),
                            StudentId = 2,
                            Term = "2025-Spring"
                        });
                });

            modelBuilder.Entity("University.Tuition.Api.Domain.Entities.Payment", b =>
                {
                    b.HasOne("University.Tuition.Api.Domain.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Tuition.Api.Domain.Entities.TuitionCharge", b =>
                {
                    b.HasOne("University.Tuition.Api.Domain.Entities.Student", "Student")
                        .WithMany("Charges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Tuition.Api.Domain.Entities.Student", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
